name: Test App

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.0

      - name: Run tests and generate test report
        run: |
          poetry install
          poetry run pytest --continue-on-collection-errors --html=pytest-report.html --self-contained-html
          exit_code=$?
          if [[ $exit_code != 0 ]]; then
            echo "Tests failed. Continuing with subsequent steps."
          fi

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: Pytest HTML Report
          path: pytest-report.html
