name: Test App

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-docker@v1

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run tests in Docker container
      run: docker run --name myapp-container myapp poetry run pytest --continue-on-collection-errors --html=/app/pytest-report.html --self-contained-html

    - name: Copy report from container to host
      run: docker cp myapp-container:/app/pytest-report.html .

    - name: Upload report artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Pytest HTML Report
        path: pytest-report.html